### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Ciolato** [alessandroamormino/ohnonico#10]
Aggiungere footer  a tutte le sezioni del sito, compresa Landing page
**Color change** (Bianco -> Giallo) sul testo quando ci si posiziona con il mouse.
Clickabili solo i link social 

![Schermata 2022-06-24 alle 12 00 52](https://user-images.githubusercontent.com/108118843/175512658-a40dcdd8-6e2b-4026-85eb-634f65514536.jpg)

**Comment by alessandroamormino** [comment]
aggiunto su home e about
